#!/bin/bash

abinfo "Building librespot..."
cargo build --release --no-default-features --features pulseaudio-backend,rodio-backend

abinfo "Installing files..."
install -m 0755 ./target/release/librespot "$PKGDIR/usr/bin/librespot"

abinfo "Installation done!"
