#!/usr/bin/bash
# This is a metapackage, and the only thing usuable is postinst script 
# to download the actual package and install it.

#!/bin/bash
#
# Copyright (c) 2015 Spotify AB
#
# This script registers menus and icons. It should be run from the top-level
# folder of the uncompressed Spotify distribution. Since this script is also run
# as a post-install task for the debian package, it will attempt to run relative
# to /usr/share/spotify if this path is available.

echo "Configuring spotify..."
spotifyPath=$PWD
if [ -e /usr/lib/spotify ]; then
  spotifyPath=/usr/lib/spotify
fi

# Add icons to the system icon folders
XDG_ICON_RESOURCE="$(command -v xdg-icon-resource 2> /dev/null)"
if [ ! -x "$XDG_ICON_RESOURCE" ]; then
  echo "Error: Could not find xdg-icon-resource" >&2
  exit 1
fi

for icon in "$spotifyPath"/icons/spotify-linux-*.png; do
  [ -e "$icon" ] || break
  size="${icon##*/spotify-linux-}"
  "$XDG_ICON_RESOURCE" install --noupdate --novendor --size "${size%.png}" "$icon" "spotify"
done
"$XDG_ICON_RESOURCE" forceupdate

# Add an entry to the system menu
XDG_DESKTOP_MENU="$(command -v xdg-desktop-menu 2> /dev/null)"
UPDATE_MENUS="$(command -v update-menus 2> /dev/null)"
if [ ! -x "$XDG_DESKTOP_MENU" ]; then
  echo "Error: Could not find xdg-desktop-menu" >&2
  exit 1
fi

# It seems the desktop file has to match the MPris name. We don't want to
# change that, so we use --novendor here instead.
"$XDG_DESKTOP_MENU" install --novendor "$spotifyPath/spotify.desktop"
if [ -x "$UPDATE_MENUS" ]; then
  "$UPDATE_MENUS"
fi

